//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2HatsTask.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public int ID { get; set; }
        public string Directory { get; set; }
        public string Field { get; set; }
        public string To { get; set; }
        public string From { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
